### ISSUE TITLE
QEMU guest agent inclusion ?

### ISSUE THREAD

**Issue by vom513** [ArchiveTeam/warrior4-vm#10]
Would love to see this for graceful shutdown of the warrior VM/OS. Thanks.

_I posted this issue over on the warrior docker repo, I guess it makes more sense to post here.  I can close that one to avoid duplication._

**Comment by vom513** [comment]
Thanks much.  In addition to the shutdown mechanism - the GA also populates the hypervisor with the system IP address of the guest, so it's nice to be able to quickly see that at a glance.

**Comment by chfoo** [comment]
Added in v4.1
