### ISSUE TITLE
fstrim periodic ?

### ISSUE THREAD

**Issue by vom513** [ArchiveTeam/warrior4-vm#14]
Looks like the image doesn't user systemd so there's no timer.  I also dont see anything in /etc/periodic

Is fstrim ran anywhere automatically ?

If not - could be it included perhaps weekly ?

Thanks.

**Comment by chfoo** [comment]
There's no fstrim timer installed. The images were meant to be used in a VM where TRIM support is not expected to be implemented or be practical. In most cases when the user wants disk space back, it's expected to just simply delete the VM. How exactly are you using the images?

**Comment by vom513** [comment]
I run mine as guests in Proxmox (Linux / KVM / QEMU).  I use the LVM-Thin storage backend.  So even when files are deleted in the guest, the blocks never really get freed on the underlying storage.

On all my other Linux guests, fstrim.timer is on by default and it frees these blocks when ran.  It's not a huge deal I suppose for the warriors, but it would be nice if they were in line with the other guests and best practices.  AFAIK running fstrim on a system even without discard on etc. underneath is harmless.

https://forum.proxmox.com/threads/local-lvm-slowly-filling-up-space-on-its-own-how-to-find-out-what-is-doing-this-and-stop-it.114286/post-494020

https://man7.org/linux/man-pages/man7/lvmthin.7.html

```
Using fstrim to increase free space in a thin pool
       Removing files in a file system on a thin LV does not generally
       return free space to the thin pool, because file systems are not
       usually mounted with the discard mount option (due to the
       performance penalty.)

       Manually running the fstrim command can return space from a thin
       LV back to the thin pool that had been used by removed files.
       This is only effective for entire thin pool chunks that have
       become unused (unused file system areas may not cover an entire
       chunk.)  Thin snapshots also keep thin pool chunks from being
       freed.  fstrim uses discards and will have no effect if the thin
       pool is configured to ignore discards.
```

**Comment by chfoo** [comment]
Oh I see. If some VMs support it now, then it definitely makes sense to include it.

**Comment by chfoo** [comment]
Added in v4.1
